x-logging: &default-logging
  driver: json-file
  options: { max-size: 10m, max-file: "3" }

services:
  ws-control:
    build:
      context: ./ws-control
    ports:
      - "8787:8787"
    environment:
      - CONTROL_TOKEN=devsecret
    logging: *default-logging
    develop:
      watch:
        - path: ./ws-control/index.ts
          target: /app/index.ts
          action: sync+restart
        - path: ./ws-control/package.json
          action: rebuild
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    logging: *default-logging
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app/bun.lock
          action: rebuild
        - path: ./app/src
          target: /app/src
          action: sync
        - path: ./app/static
          target: /app/static
          action: sync
        - path: ./app/vite.config.js
          target: /app/vite.config.js
          action: sync+restart
